[package]
name = "squire_lib"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
authors = ["TylerBloom <tylerbloom2222@gmail.com>"]

[lib]
crate-type = ["lib", "staticlib"]

[dependencies]
#In-house deps
cycle_map = { version = "0.1.1", features = ["serde"] }
mtgjson = { git = "https://github.com/TylerBloom/mtgjson-rust-sdk", branch = "main" }

uuid = { version = "0.8", features = ["serde", "v4"] }
serde = { version = "1.0", features = ["derive"] }
libc = { version = "0.2", optional = true }

[build-dependencies]
cbindgen = { version = "0.20.0", optional = true}

[features]
ffi = ["cbindgen", "libc"]
