[package]
name = "squire_sdk"
version = "0.1.0-pre-alpha.1"
edition = "2021"
license = "GPL-3.0"
authors = ["TylerBloom <tylerbloom2222@gmail.com>"]

[features]
default = ["rocket"]

[dependencies]
# In-House deps
mtgjson = { git = "https://github.com/TylerBloom/mtgjson-rust-sdk", branch = "main" }
squire_lib = { path = "../squire_lib" }

rocket = { version = "0.5.0-rc.1", optional = true }
uuid = { version = "1.1.2", features = ["serde", "v4"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.68" }
